name: bg

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment


jobs:
  deploy_to_staging:
    environment: ${{ inputs.environment }}  
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo ${{ github.event.deployment.environment }}
