name: bg

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment


jobs:
  job1:
    environment: ${{ inputs.environment }}  
    if: inputs.environment == 'PRODUCTION'
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}

  job2:
    environment: ${{ inputs.environment }}  
    if: inputs.environment == 'DEVELOPMENT'
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
