name: bg

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment


jobs:
  job1:
    environment: ${{ inputs.environment }}  
    if: inputs.environment == 'PRODUCTION'
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}

  job2:
    environment: ${{ inputs.environment }}  
    if: inputs.environment == 'DEVELOPMENT'
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: |
         mkdir dist
         cd dist
         echo ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}  >> hey.txt
         ls -al
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4
       with:
        name: frog
        path: dist/
     - name: echo
       run: |
         ls -al
