name: BlueGreen

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

      node-version:
        description: Optionally pass the Node version. default value is 20.5.0
        required: false
        type: string
        default: 20.5.0
      
      build-cmd:
        description: Optionally pass npm build command. default value is 'npm run build'
        required: false
        type: string
        default: npm run build

jobs:
  job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2


    - name: Info
      run: | 
          CLOUDFRONT_ID="E1GYKG6MMV1XI4"
          echo $CLOUDFRONT_ID
          S3_BUCKET=`aws cloudfront get-distribution --id $CLOUDFRONT_ID`
          echo $S3_BUCKET
          PRIMARY_ETAG=`aws cloudfront get-distribution-config --id $CLOUDFRONT_ID --query 'ETag' --output text`
          echo $PRIMARY_ETAG

