name: BlueGreen

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

      node-version:
        description: Optionally pass the Node version. default value is 20.5.0
        required: false
        type: string
        default: 20.5.0
      
      build-cmd:
        description: Optionally pass npm build command. default value is 'npm run build'
        required: false
        type: string
        default: npm run build

jobs:
  job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2


    - name: Info
      run: | 
          sudo apt-get install jq -y
          CLOUDFRONT_ID="E1GYKG6MMV1XI4"
          echo $CLOUDFRONT_ID
          echo ${{ vars.STAGING_CLOUDFRONT_ID }}
          echo "--------------------"
          S3_BUCKET=`aws cloudfront get-distribution --id $CLOUDFRONT_ID | jq -r '.Distribution.DistributionConfig.Origins.Items[] | select(.Id == "default").DomainName'|cut -d "." -f1`
          echo $S3_BUCKET
          PROD_S3_BUCKET=`aws cloudfront get-distribution --id $CLOUDFRONT_ID | jq -r '.Distribution.DistributionConfig.Origins.Items[] | select(.Id == "default").DomainName'|cut -d "." -f1`
          STAGING_S3_BUCKET=`aws cloudfront get-distribution --id ${{ vars.STAGING_CLOUDFRONT_ID }} | jq -r '.Distribution.DistributionConfig.Origins.Items[] | select(.Id == "default").DomainName'|cut -d "." -f1`
          PRIMARY_ETAG=`aws cloudfront get-distribution-config --id $CLOUDFRONT_ID --query 'ETag' --output text`
          STAGING_ETAG=`aws cloudfront get-distribution-config --id ${{ vars.STAGING_CLOUDFRONT_ID }} --query 'ETag' --output text`
          echo $STAGING_S3_BUCKET
          echo $PRIMARY_ETAG $STAGING_ETAG

