name: Deploy Selected

on:
  workflow_dispatch:
    inputs:
      DEVELOPMENT:
        description: 'Deploy to DEVELOPMENT'
        type: boolean
        default: true
        required: false
      STAGING:
          description: 'Deploy to STAGING'
          type: boolean
          default: true
          required: false
      QA:
          description: 'Deploy to QA'
          type: boolean
          default: true
          required: false
      PRODUCTION:
        description: 'Deploy to PRODUCTION'
        type: boolean
        default: true
        required: false

      node-version:
        description: Optionally pass the Node version. default value is 12.x
        required: false
        type: string
        default: 20.5.0
      
      build-cmd:
        description: Optionally pass npm build command. default value is 'npm run build'
        required: false
        type: string
        default: npm run build

jobs:
  deploy-matrix:
    strategy:
      fail-fast: false
      matrix:
        location: 
           - DEVELOPMENT
           - STAGING
           - QA
           - PRODUCTION
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Deploy to DEVELOPMENT
        if: ${{ matrix.location == 'DEVELOPMENT' && inputs.DEVELOPMENT}}
        uses: ./.github/workflows/deploy_each.yml
        with:
           location: ${{ matrix.location }}

